import React, { createContext, useState, useContext, useCallback, useMemo, useEffect } from 'react';

const translations = {
  en: {
    home: "Home",
    about: "About",
    projects: "Projects",
    discordBots: "Discord Bots",
    contact: "Contact",
    technologies: "Technologies",

    helloIm: "Hello, I'm",
    iBuild: "I build",
    amazingWebsites: "amazing websites",
    discordBots2: "Discord bots",
    userExperiences: "user experiences",
    digitalSolutions: "digital solutions",
    customApplications: "custom applications",
    heroDescription: "Frontend developer and Discord bot specialist focused on creating exceptional web applications and intelligent automation solutions",
    viewMyWork: "View My Work",
    letsConnect: "Let's Connect",
    github: "GitHub",
    projectsCompleted: "Projects Completed",
    discordBotsCount: "Discord Bots",
    supportAvailable: "Support Available",

    aboutMe: "About Me",
    aboutTagline: "Frontend developer and Discord bot specialist focused on creating exceptional digital experiences.",
    aboutDescription: "Hi! I'm orzz5, a frontend developer and Discord bot specialist who creates beautiful, functional digital experiences. I help bring ideas to life through React applications and custom Discord bots.",
    problemSolver: "Problem Solver",
    creativeThinker: "Creative Thinker",
    teamPlayer: "Team Player",
    fastLearner: "Fast Learner",
    cleanCode: "Clean Code",
    performance: "Performance",
    versionControl: "Version Control",
    debugging: "Debugging",
    expert: "Expert",
    frontendDev: "Frontend Development",
    backendDev: "Backend Development",
    mobileDev: "Mobile Development",
    cloudDev: "Cloud & DevOps",
    skillsExpertise: "Skills & Expertise",
    whatIOffer: "What I Offer",
    webDevTitle: "Web Development",
    webDevDesc: "Building responsive, fast, and beautiful web applications with modern technologies",
    discordDevTitle: "Discord Bots",
    discordDevDesc: "Custom Discord bots for moderation, entertainment, automation, and community management",
    designTitle: "UI/UX Design",
    designDesc: "Creating intuitive and visually appealing user interfaces that delight users",
    perfOptTitle: "Performance Optimization",
    perfOptDesc: "Optimizing applications for speed, SEO, and best user experience",

    whatIUse: "What I Use",
    toolsDaily: "Tools and technologies I work with daily",

    projectsTitle: "Projects",
    projectsTagline: "Showcasing my latest work in frontend development and Discord bot creation",
    allProjects: "All Projects",
    webApps: "Web Apps",
    projectsComingSoon: "Projects Coming Soon",
    projectsSoonDesc: "I'm currently working on some exciting projects that will be showcased here soon. Check back later to see my latest work in web development and Discord bot creation.",
    getNotified: "Get Notified",
    viewAllProjects: "View All Projects",
    keyFeatures: "Key Features",
    featuresCount: "more features",
    
    // Bots Project
    botsProjectTitle: "bots.orzz.website",
    botsProjectDesc: "A website to test all my created bots",
    clickToEnter: "Click anywhere to enter",
    preview: "Preview",

    discordBotDev: "Discord Bot Development",
    discordDesc: "Create powerful, custom Discord bots that enhance your server experience and automate community management",
    botTypesTitle: "Bot Types I Create",
    whyChooseTitle: "Why Choose My Bots?",
    popular: "Popular",
    moderationTitle: "Moderation Bots",
    moderationDesc: "Advanced server management with automated moderation tools",
    musicTitle: "Music Bots",
    musicDesc: "High-quality music playback with extensive library support",
    gamingTitle: "Gaming Bots",
    gamingDesc: "Interactive games and gaming community management tools",
    utilityTitle: "Utility Bots",
    utilityDesc: "Helpful tools for server management and user convenience",
    economyTitle: "Economy Bots",
    economyDesc: "Virtual currency systems with shops and rewards",
    customBotsTitle: "Custom Bots",
    customBotsDesc: "Tailored solutions for your specific server needs",
    lightningFast: "Lightning Fast",
    lightningFastDesc: "Optimized performance with minimal latency",
    dataStorage: "Data Storage",
    dataStorageDesc: "Secure database solutions for persistent data",
    secureReliable: "Secure & Reliable",
    secureReliableDesc: "Enterprise-grade security and 99.9% uptime",
    analyticsDashboard: "Analytics Dashboard",
    analyticsDashboardDesc: "Detailed insights and usage statistics",
    multiLanguage: "Multi-language",
    multiLanguageDesc: "Support for multiple languages and regions",
    support247: "24/7 Support",
    support247Desc: "Round-the-clock maintenance and updates",

    getInTouch: "Get in Touch",
    contactTagline: "Send me a message and I'll get back to you as soon as possible.",
    connectOnSocial: "Connect on Social",
    sendMessage: "Send a Message",
    name: "Name",
    emailAddress: "Email Address",
    subject: "Subject",
    projectType: "Project Type",
    message: "Message",
    send: "Send Message",
    sending: "Sending...",
    selectProjectType: "Select a project type",
    webDevelopment: "Web Development",
    discordBot: "Discord Bot",
    uiuxDesign: "UI/UX Design",
    mobileApp: "Mobile App",
    messagePlaceholder: "Tell me about your project...",
    messageSuccess: "Message Sent Successfully!",
    messageSuccessDesc: "Thank you for reaching out. I'll get back to you soon.",
    messageError: "Failed to send message. Please try again.",

    footerDesc: "Creating exceptional digital experiences and powerful Discord bots that make communities thrive.",
    quickLinks: "Quick Links",
    services: "Services",
    consulting: "Consulting",
    backToTop: "Back to top",
    rights: "All rights reserved. Made with",
    andLotsOf: "and lots of",

    discordPresence: "Discord Presence",
    online: "Online",
    idle: "Idle",
    dnd: "Do Not Disturb",
    offline: "Offline",
    available: "Available",
    viewProfile: "View Profile",

    autoModeration: "Auto moderation",
    warningSystem: "Warning system",
    roleManagement: "Role management",
    auditLogging: "Audit logging",
    youtubeSpotify: "YouTube/Spotify",
    playlists: "Playlists",
    audioEffects: "Audio effects",
    voiceChannels: "Voice channels",
    miniGames: "Mini games",
    tournaments: "Tournaments",
    statsTracking: "Stats tracking",
    lfgSystem: "LFG system",
    customCommands: "Custom commands",
    reminders: "Reminders",
    polls: "Polls",
    welcomeMessages: "Welcome messages",
    virtualCurrency: "Virtual currency",
    shopSystem: "Shop system",
    dailyRewards: "Daily rewards",
    gamblingGames: "Gambling games",
    customFeatures: "Custom features",
    apiIntegration: "API integration",
    databaseDesign: "Database design",
    uniqueCommands: "Unique commands",
  },

  es: {
    home: "Inicio",
    about: "Sobre Mí",
    projects: "Proyectos",
    discordBots: "Bots de Discord",
    contact: "Contacto",
    technologies: "Tecnologías",

    helloIm: "Hola, soy",
    iBuild: "Desarrollo",
    amazingWebsites: "sitios web increíbles",
    discordBots2: "bots de Discord",
    userExperiences: "experiencias de usuario",
    digitalSolutions: "soluciones digitales",
    customApplications: "aplicaciones personalizadas",
    heroDescription: "Desarrollador frontend y especialista en bots de Discord enfocado en crear aplicaciones web excepcionales y soluciones de automatización inteligentes.",
    viewMyWork: "Ver mi trabajo",
    letsConnect: "Conectemos",
    github: "GitHub",
    projectsCompleted: "Proyectos Completados",
    discordBotsCount: "Bots de Discord",
    supportAvailable: "Soporte Disponible",

    aboutMe: "Sobre Mí",
    aboutTagline: "Desarrollador frontend y especialista en bots de Discord enfocado en crear experiencias digitales excepcionales.",
    aboutDescription: "¡Hola! Soy orzz5, un desarrollador frontend y especialista en bots de Discord que crea experiencias digitales hermosas y funcionales. Ayudo a dar vida a las ideas a través de aplicaciones React y bots de Discord personalizados.",
    problemSolver: "Resolución de Problemas",
    creativeThinker: "Pensamiento Creativo",
    teamPlayer: "Trabajo en Equipo",
    fastLearner: "Aprendizaje Rápido",
    cleanCode: "Código Limpio",
    performance: "Rendimiento",
    versionControl: "Control de Versiones",
    debugging: "Depuración",
    expert: "Experto",
    frontendDev: "Desarrollo Frontend",
    backendDev: "Desarrollo Backend",
    mobileDev: "Desarrollo Móvil",
    cloudDev: "Cloud & DevOps",
    skillsExpertise: "Habilidades y Experiencia",
    whatIOffer: "Lo que Ofrezco",
    webDevTitle: "Desarrollo Web",
    webDevDesc: "Construcción de aplicaciones web responsivas, rápidas y hermosas con tecnologías modernas.",
    discordDevTitle: "Bots de Discord",
    discordDevDesc: "Bots personalizados para moderación, entretenimiento, automatización y gestión de comunidades.",
    designTitle: "Diseño UI/UX",
    designDesc: "Creación de interfaces de usuario intuitivas y visualmente atractivas que cautivan a los usuarios.",
    perfOptTitle: "Optimización de Rendimiento",
    perfOptDesc: "Optimización de aplicaciones para velocidad, SEO y la mejor experiencia de usuario.",

    whatIUse: "Lo que Utilizo",
    toolsDaily: "Herramientas y tecnologías con las que trabajo a diario.",

    projectsTitle: "Proyectos",
    projectsTagline: "Muestra de mis últimos trabajos en desarrollo frontend y creación de bots de Discord.",
    allProjects: "Todos los Proyectos",
    webApps: "Apps Web",
    projectsComingSoon: "Próximamente",
    projectsSoonDesc: "Actualmente estoy trabajando en proyectos emocionantes que se mostrarán aquí pronto. ¡Vuelve más tarde!",
    getNotified: "Avísame",
    viewAllProjects: "Ver Todos los Proyectos",
    keyFeatures: "Características Clave",
    featuresCount: "más funciones",

    // Bots Project
    botsProjectTitle: "bots.orzz.website",
    botsProjectDesc: "Un sitio web para probar todos mis bots creados.",
    clickToEnter: "Haz clic en cualquier lugar para entrar",
    preview: "Vista Previa",

    discordBotDev: "Desarrollo de Bots de Discord",
    discordDesc: "Crea bots de Discord potentes y personalizados que mejoran la experiencia de tu servidor y automatizan la gestión comunitaria.",
    botTypesTitle: "Tipos de Bots que Creo",
    whyChooseTitle: "¿Por qué elegir mis bots?",
    popular: "Popular",
    moderationTitle: "Bots de Moderación",
    moderationDesc: "Gestión avanzada de servidores con herramientas de moderación automatizadas.",
    musicTitle: "Bots de Música",
    musicDesc: "Reproducción de música de alta calidad con soporte para amplias librerías.",
    gamingTitle: "Bots de Juegos",
    gamingDesc: "Juegos interactivos y herramientas de gestión para comunidades gaming.",
    utilityTitle: "Bots de Utilidad",
    utilityDesc: "Herramientas útiles para la gestión de servidores y comodidad del usuario.",
    economyTitle: "Bots de Economía",
    economyDesc: "Sistemas de moneda virtual con tiendas y recompensas.",
    customBotsTitle: "Bots Personalizados",
    customBotsDesc: "Soluciones a medida para las necesidades específicas de tu servidor.",
    lightningFast: "Velocidad Extrema",
    lightningFastDesc: "Rendimiento optimizado con la mínima latencia.",
    dataStorage: "Almacenamiento de Datos",
    dataStorageDesc: "Soluciones de base de datos seguras para datos persistentes.",
    secureReliable: "Seguro y Confiable",
    secureReliableDesc: "Seguridad de nivel empresarial y 99.9% de tiempo de actividad.",
    analyticsDashboard: "Panel de Análisis",
    analyticsDashboardDesc: "Información detallada y estadísticas de uso.",
    multiLanguage: "Multi-idioma",
    multiLanguageDesc: "Soporte para múltiples idiomas y regiones.",
    support247: "Soporte 24/7",
    support247Desc: "Mantenimiento y actualizaciones constantes.",

    getInTouch: "Ponte en Contacto",
    contactTagline: "Envíame un mensaje y te responderé lo antes posible.",
    connectOnSocial: "Redes Sociales",
    sendMessage: "Enviar Mensaje",
    name: "Nombre",
    emailAddress: "Correo Electrónico",
    subject: "Asunto",
    projectType: "Tipo de Proyecto",
    message: "Mensaje",
    send: "Enviar Mensaje",
    sending: "Enviando...",
    selectProjectType: "Selecciona el tipo de proyecto",
    webDevelopment: "Desarrollo Web",
    discordBot: "Bot de Discord",
    uiuxDesign: "Diseño UI/UX",
    mobileApp: "App Móvil",
    messagePlaceholder: "Cuéntame sobre tu proyecto...",
    messageSuccess: "¡Mensaje Enviado!",
    messageSuccessDesc: "Gracias por contactarme. Te responderé muy pronto.",
    messageError: "Error al enviar el mensaje. Inténtalo de nuevo.",

    footerDesc: "Creando experiencias digitales excepcionales y bots de Discord potentes que hacen prosperar a las comunidades.",
    quickLinks: "Enlaces Rápidos",
    services: "Servicios",
    consulting: "Consultoría",
    backToTop: "Volver arriba",
    rights: "Todos los derechos reservados. Hecho con",
    andLotsOf: "y mucho",

    discordPresence: "Presencia en Discord",
    online: "En línea",
    idle: "Ausente",
    dnd: "No molestar",
    offline: "Desconectado",
    available: "Disponible",
    viewProfile: "Ver perfil",

    autoModeration: "Auto moderación",
    warningSystem: "Sistema de avisos",
    roleManagement: "Gestión de roles",
    auditLogging: "Registros de auditoría",
    youtubeSpotify: "YouTube/Spotify",
    playlists: "Listas de reproducción",
    audioEffects: "Efectos de audio",
    voiceChannels: "Canales de voz",
    miniGames: "Mini juegos",
    tournaments: "Torneos",
    statsTracking: "Estadísticas",
    lfgSystem: "Sistema LFG",
    customCommands: "Comandos personalizados",
    reminders: "Recordatorios",
    polls: "Encuestas",
    welcomeMessages: "Mensajes de bienvenida",
    virtualCurrency: "Moneda virtual",
    shopSystem: "Sistema de tienda",
    dailyRewards: "Premios diarios",
    gamblingGames: "Juegos de azar",
    customFeatures: "Funciones a medida",
    apiIntegration: "Integración de API",
    databaseDesign: "Diseño de base de datos",
    uniqueCommands: "Comandos únicos",
  },

  fr: {
    home: "Accueil",
    about: "À Propos",
    projects: "Projets",
    discordBots: "Bots Discord",
    contact: "Contact",
    technologies: "Technologies",

    helloIm: "Bonjour, je suis",
    iBuild: "Je conçois",
    amazingWebsites: "des sites web incroyables",
    discordBots2: "des bots Discord",
    userExperiences: "des expériences utilisateur",
    digitalSolutions: "des solutions numériques",
    customApplications: "des applications personnalisées",
    heroDescription: "Développeur frontend et spécialiste des bots Discord, axé sur la création d'applications web exceptionnelles et de solutions d'automatisation intelligentes.",
    viewMyWork: "Voir mon travail",
    letsConnect: "Connectons-nous",
    github: "GitHub",
    projectsCompleted: "Projets Terminés",
    discordBotsCount: "Bots Discord",
    supportAvailable: "Support Disponible",

    aboutMe: "À Propos de Moi",
    aboutTagline: "Développeur frontend et spécialiste des bots Discord, axé sur la création d'expériences numériques exceptionnelles.",
    aboutDescription: "Salut ! Je suis orzz5, un développeur frontend et spécialiste des bots Discord qui crée des expériences numériques belles et fonctionnelles. J'aide à donner vie aux idées grâce à des applications React et des bots Discord personnalisés.",
    problemSolver: "Résolution de Problèmes",
    creativeThinker: "Pensée Créative",
    teamPlayer: "Esprit d'Équipe",
    fastLearner: "Apprentissage Rapide",
    cleanCode: "Code Propre",
    performance: "Performance",
    versionControl: "Contrôle de Version",
    debugging: "Débogage",
    expert: "Expert",
    frontendDev: "Développement Frontend",
    backendDev: "Développement Backend",
    mobileDev: "Développement Mobile",
    cloudDev: "Cloud & DevOps",
    skillsExpertise: "Compétences et Expertise",
    whatIOffer: "Ce que je propose",
    webDevTitle: "Développement Web",
    webDevDesc: "Construction d'applications web réactives, rapides et belles avec des technologies modernes.",
    discordDevTitle: "Bots Discord",
    discordDevDesc: "Bots personnalisés pour la modération, le divertissement, l'automatisation et la gestion de communauté.",
    designTitle: "Design UI/UX",
    designDesc: "Création d'interfaces utilisateur intuitives et visuellement attrayantes qui ravissent les utilisateurs.",
    perfOptTitle: "Optimisation des Performances",
    perfOptDesc: "Optimisation des applications pour la vitesse, le SEO et la meilleure expérience utilisateur.",

    whatIUse: "Ce que j'utilise",
    toolsDaily: "Outils et technologies avec lesquels je travaille quotidiennement.",

    projectsTitle: "Projets",
    projectsTagline: "Présentation de mes derniers travaux en développement frontend et création de bots Discord.",
    allProjects: "Tous les Projets",
    webApps: "Apps Web",
    projectsComingSoon: "Bientôt disponible",
    projectsSoonDesc: "Je travaille actuellement sur des projets passionnants qui seront présentés ici bientôt. Revenez plus tard !",
    getNotified: "M'avertir",
    viewAllProjects: "Voir Tous les Projets",
    keyFeatures: "Caractéristiques Clés",
    featuresCount: "plus de fonctions",

    // Bots Project
    botsProjectTitle: "bots.orzz.website",
    botsProjectDesc: "Un site web pour tester tous mes bots créés.",
    clickToEnter: "Cliquez n'importe où pour entrer",
    preview: "Aperçu",

    discordBotDev: "Développement de Bots Discord",
    discordDesc: "Créez des bots Discord puissants et personnalisés qui améliorent l'expérience de votre serveur et automatisent la gestion de communauté.",
    botTypesTitle: "Types de bots que je crée",
    whyChooseTitle: "Pourquoi choisir mes bots ?",
    popular: "Populaire",
    moderationTitle: "Bots de Modération",
    moderationDesc: "Gestion avancée de serveur avec des outils de modération automatisés.",
    musicTitle: "Bots de Musique",
    musicDesc: "Lecture de musique de haute qualité avec une prise en charge étendue des bibliothèques.",
    gamingTitle: "Bots de Jeux",
    gamingDesc: "Jeux interactifs et outils de gestion de communauté de joueurs.",
    utilityTitle: "Bots d'Utilité",
    utilityDesc: "Outils utiles pour la gestion de serveur et le confort des utilisateurs.",
    economyTitle: "Bots d'Économie",
    economyDesc: "Systèmes de monnaie virtuelle avec boutiques et récompenses.",
    customBotsTitle: "Bots Personnalisés",
    customBotsDesc: "Solutions sur mesure pour les besoins spécifiques de votre serveur.",
    lightningFast: "Vitesse Éclair",
    lightningFastDesc: "Performances optimisées avec une latence minimale.",
    dataStorage: "Stockage de Données",
    dataStorageDesc: "Solutions de base de données sécurisées pour les données persistantes.",
    secureReliable: "Sûr et Fiable",
    secureReliableDesc: "Sécurité de niveau entreprise et 99,9 % de temps de fonctionnement.",
    analyticsDashboard: "Tableau de Bord Analytique",
    analyticsDashboardDesc: "Informations détaillées et statistiques d'utilisation.",
    multiLanguage: "Multi-langue",
    multiLanguageDesc: "Support pour plusieurs langues et régions.",
    support247: "Support 24/7",
    support247Desc: "Maintenance et mises à jour constantes.",

    getInTouch: "Contactez-moi",
    contactTagline: "Envoyez-moi un message et je vous répondrai dès que possible.",
    connectOnSocial: "Réseaux Sociaux",
    sendMessage: "Envoyer un Message",
    name: "Nom",
    emailAddress: "Adresse e-mail",
    subject: "Sujet",
    projectType: "Type de Projet",
    message: "Message",
    send: "Envoyer le Message",
    sending: "Envoi en cours...",
    selectProjectType: "Sélectionnez un type de projet",
    webDevelopment: "Développement Web",
    discordBot: "Bot Discord",
    uiuxDesign: "Design UI/UX",
    mobileApp: "App Mobile",
    messagePlaceholder: "Parlez-moi de votre projet...",
    messageSuccess: "Message Envoyé !",
    messageSuccessDesc: "Merci de m'avoir contacté. Je vous répondrai très bientôt.",
    messageError: "Échec de l'envoi du message. Veuillez réessayer.",

    footerDesc: "Création d'expériences numériques exceptionnelles et de bots Discord puissants qui font prospérer les communautés.",
    quickLinks: "Liens Rapides",
    services: "Services",
    consulting: "Consultation",
    backToTop: "Retour en haut",
    rights: "Tous droits réservés. Fait avec",
    andLotsOf: "et beaucoup de",

    discordPresence: "Présence Discord",
    online: "En ligne",
    idle: "Inactif",
    dnd: "Ne pas déranger",
    offline: "Hors ligne",
    available: "Disponible",
    viewProfile: "Voir le profil",

    autoModeration: "Auto modération",
    warningSystem: "Système d'avertissement",
    roleManagement: "Gestion des rôles",
    auditLogging: "Logs d'audit",
    youtubeSpotify: "YouTube/Spotify",
    playlists: "Listes de lecture",
    audioEffects: "Effets audio",
    voiceChannels: "Salons vocaux",
    miniGames: "Mini-jeux",
    tournaments: "Tournois",
    statsTracking: "Suivi des stats",
    lfgSystem: "Système LFG",
    customCommands: "Commandes personnalisées",
    reminders: "Rappels",
    polls: "Sondages",
    welcomeMessages: "Messages de bienvenue",
    virtualCurrency: "Monnaie virtuelle",
    shopSystem: "Système de boutique",
    dailyRewards: "Récompenses quotidiennes",
    gamblingGames: "Jeux de hasard",
    customFeatures: "Fonctionnalités sur mesure",
    apiIntegration: "Intégration API",
    databaseDesign: "Conception de base de données",
    uniqueCommands: "Commandes uniques",
  }
};

const LanguageContext = createContext();

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = useCallback((key) => {
    return translations[language][key] || translations['en'][key] || key;
  }, [language]);

  const changeLanguage = useCallback((lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  }, []);

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
  }, []);

  const value = useMemo(() => ({
    language,
    t,
    changeLanguage
  }), [language, t, changeLanguage]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
