import React, { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    // Navigation
    home: "Home",
    about: "About",
    projects: "Projects",
    discordBots: "Discord Bots",
    contact: "Contact",
    technologies: "Technologies",

    // Hero Section
    helloIm: "Hello, I'm",
    iBuild: "I build",
    amazingWebsites: "amazing websites",
    discordBots2: "Discord bots",
    userExperiences: "user experiences",
    digitalSolutions: "digital solutions",
    customApplications: "custom applications",
    heroDescription: "Frontend developer and Discord bot specialist focused on creating exceptional web applications and intelligent automation solutions",
    viewMyWork: "View My Work",
    letsConnect: "Let's Connect",
    github: "GitHub",
    projectsCompleted: "Projects Completed",
    discordBotsCount: "Discord Bots",
    supportAvailable: "Support Available",

    // About Section
    aboutMe: "About Me",
    aboutTagline: "Frontend developer and Discord bot specialist focused on creating exceptional digital experiences.",
    aboutDescription: "Hi! I'm orzz5, a frontend developer and Discord bot specialist who creates beautiful, functional digital experiences. I help bring ideas to life through React applications and custom Discord bots.",
    problemSolver: "Problem Solver",
    creativeThinker: "Creative Thinker",
    teamPlayer: "Team Player",
    fastLearner: "Fast Learner",
    cleanCode: "Clean Code",
    performance: "Performance",
    versionControl: "Version Control",
    debugging: "Debugging",
    expert: "Expert",
    frontendDev: "Frontend Development",
    backendDev: "Backend Development",
    mobileDev: "Mobile Development",
    cloudDev: "Cloud & DevOps",
    skillsExpertise: "Skills & Expertise",
    whatIOffer: "What I Offer",
    webDevTitle: "Web Development",
    webDevDesc: "Building responsive, fast, and beautiful web applications with modern technologies",
    discordDevTitle: "Discord Bots",
    discordDevDesc: "Custom Discord bots for moderation, entertainment, automation, and community management",
    designTitle: "UI/UX Design",
    designDesc: "Creating intuitive and visually appealing user interfaces that delight users",
    perfOptTitle: "Performance Optimization",
    perfOptDesc: "Optimizing applications for speed, SEO, and best user experience",

    // Technologies Section
    whatIUse: "What I Use",
    toolsDaily: "Tools and technologies I work with daily",

    // Projects Section
    projectsTitle: "Projects",
    projectsTagline: "Coming soon - showcasing my latest work in frontend development and Discord bot creation",
    allProjects: "All Projects",
    webApps: "Web Apps",
    projectsComingSoon: "Projects Coming Soon",
    projectsSoonDesc: "I'm currently working on some exciting projects that will be showcased here soon. Check back later to see my latest work in web development and Discord bot creation.",
    getNotified: "Get Notified",
    viewAllProjects: "View All Projects",
    keyFeatures: "Key Features:",

    // Discord Services Section
    discordBotDev: "Discord Bot Development",
    discordDesc: "Create powerful, custom Discord bots that enhance your server experience and automate community management",
    botTypesTitle: "Bot Types I Create",
    whyChooseTitle: "Why Choose My Bots?",
    popular: "Popular",
    featuresCount: "more features",
    moderationTitle: "Moderation Bots",
    moderationDesc: "Advanced server management with automated moderation tools",
    musicTitle: "Music Bots",
    musicDesc: "High-quality music playback with extensive library support",
    gamingTitle: "Gaming Bots",
    gamingDesc: "Interactive games and gaming community management tools",
    utilityTitle: "Utility Bots",
    utilityDesc: "Helpful tools for server management and user convenience",
    economyTitle: "Economy Bots",
    economyDesc: "Virtual currency systems with shops and rewards",
    customBotsTitle: "Custom Bots",
    customBotsDesc: "Tailored solutions for your specific server needs",
    lightningFast: "Lightning Fast",
    lightningFastDesc: "Optimized performance with minimal latency",
    dataStorage: "Data Storage",
    dataStorageDesc: "Secure database solutions for persistent data",
    secureReliable: "Secure & Reliable",
    secureReliableDesc: "Enterprise-grade security and 99.9% uptime",
    analyticsDashboard: "Analytics Dashboard",
    analyticsDashboardDesc: "Detailed insights and usage statistics",
    multiLanguage: "Multi-language",
    multiLanguageDesc: "Support for multiple languages and regions",
    support247: "24/7 Support",
    support247Desc: "Round-the-clock maintenance and updates",

    // Contact Section
    getInTouch: "Get in Touch",
    contactTagline: "Send me a message and I'll get back to you as soon as possible.",
    connectOnSocial: "Connect on Social",
    sendMessage: "Send a Message",
    name: "Name",
    emailAddress: "Email Address",
    subject: "Subject",
    projectType: "Project Type",
    message: "Message",
    send: "Send Message",
    sending: "Sending...",
    selectProjectType: "Select a project type",
    webDevelopment: "Web Development",
    discordBot: "Discord Bot",
    uiuxDesign: "UI/UX Design",
    mobileApp: "Mobile App",
    messagePlaceholder: "Tell me about your project...",
    messageSuccess: "Message Sent Successfully!",
    messageSuccessDesc: "Thank you for reaching out. I'll get back to you soon.",
    messageError: "Failed to send message. Please try again.",

    // Footer
    footerDesc: "Creating exceptional digital experiences and powerful Discord bots that make communities thrive.",
    quickLinks: "Quick Links",
    services: "Services",
    consulting: "Consulting",
    backToTop: "Back to top",
    rights: "All rights reserved. Made with",
    andLotsOf: "and lots of",

    // Discord Presence
    discordPresence: "Discord Presence",
    online: "Online",
    idle: "Idle",
    dnd: "Do Not Disturb",
    offline: "Offline",
    available: "Available",
    viewProfile: "View Profile",

    // Bot Features
    autoModeration: "Auto moderation",
    warningSystem: "Warning system",
    roleManagement: "Role management",
    auditLogging: "Audit logging",
    youtubeSpotify: "YouTube/Spotify",
    playlists: "Playlists",
    audioEffects: "Audio effects",
    voiceChannels: "Voice channels",
    miniGames: "Mini games",
    tournaments: "Tournaments",
    statsTracking: "Stats tracking",
    lfgSystem: "LFG system",
    customCommands: "Custom commands",
    reminders: "Reminders",
    polls: "Polls",
    welcomeMessages: "Welcome messages",
    virtualCurrency: "Virtual currency",
    shopSystem: "Shop system",
    dailyRewards: "Daily rewards",
    gamblingGames: "Gambling games",
    customFeatures: "Custom features",
    apiIntegration: "API integration",
    databaseDesign: "Database design",
    uniqueCommands: "Unique commands",
  },

  es: {
    // Navigation
    home: "Inicio",
    about: "Sobre Mí",
    projects: "Proyectos",
    discordBots: "Bots de Discord",
    contact: "Contacto",
    technologies: "Tecnologías",

    // Hero Section
    helloIm: "Hola, soy",
    iBuild: "Creo",
    amazingWebsites: "sitios web increíbles",
    discordBots2: "bots de Discord",
    userExperiences: "experiencias de usuario",
    digitalSolutions: "soluciones digitales",
    customApplications: "aplicaciones personalizadas",
    heroDescription: "Desarrollador frontend y especialista en bots de Discord enfocado en crear aplicaciones web excepcionales y soluciones de automatización inteligentes",
    viewMyWork: "Ver mi trabajo",
    letsConnect: "Conectemos",
    github: "GitHub",
    projectsCompleted: "Proyectos Completados",
    discordBotsCount: "Bots de Discord",
    supportAvailable: "Soporte Disponible",

    // About Section
    aboutMe: "Sobre Mí",
    aboutTagline: "Desarrollador frontend y especialista en bots de Discord enfocado en crear experiencias digitales excepcionales.",
    aboutDescription: "¡Hola! Soy orzz5, un desarrollador frontend y especialista en bots de Discord que crea experiencias digitales hermosas y funcionales. Ayudo a dar vida a las ideas a través de aplicaciones React y bots de Discord personalizados.",
    problemSolver: "Resolutor de problemas",
    creativeThinker: "Pensador creativo",
    teamPlayer: "Jugador de equipo",
    fastLearner: "Aprendizaje rápido",
    cleanCode: "Código Limpio",
    performance: "Rendimiento",
    versionControl: "Control de Versiones",
    debugging: "Depuración",
    expert: "Experto",
    frontendDev: "Desarrollo Frontend",
    backendDev: "Desarrollo Backend",
    mobileDev: "Desarrollo Móvil",
    cloudDev: "Cloud y DevOps",
    skillsExpertise: "Habilidades y Experiencia",
    whatIOffer: "Lo que ofrezco",
    webDevTitle: "Desarrollo Web",
    webDevDesc: "Construcción de aplicaciones web responsivas, rápidas y hermosas con tecnologías modernas",
    discordDevTitle: "Bots de Discord",
    discordDevDesc: "Bots de Discord personalizados para moderación, entretenimiento, automatización y gestión de comunidades",
    designTitle: "Diseño UI/UX",
    designDesc: "Creación de interfaces de usuario intuitivas y visualmente atractivas que encantan a los usuarios",
    perfOptTitle: "Optimización de Rendimiento",
    perfOptDesc: "Optimización de aplicaciones para velocidad, SEO y la mejor experiencia de usuario",

    // Technologies Section
    whatIUse: "Lo que utilizo",
    toolsDaily: "Herramientas y tecnologías con las que trabajo a diario",

    // Projects Section
    projectsTitle: "Proyectos",
    projectsTagline: "Próximamente - mostrando mi trabajo más reciente en desarrollo frontend y creación de bots de Discord",
    allProjects: "Todos los proyectos",
    webApps: "Aplicaciones Web",
    projectsComingSoon: "Proyectos Próximamente",
    projectsSoonDesc: "Actualmente estoy trabajando en algunos proyectos emocionantes que se mostrarán aquí pronto. Vuelve más tarde para ver mi trabajo más reciente.",
    getNotified: "Recibir notificaciones",
    viewAllProjects: "Ver todos los proyectos",
    keyFeatures: "Características clave:",

    // Discord Services Section
    discordBotDev: "Desarrollo de Bots de Discord",
    discordDesc: "Crea bots de Discord potentes y personalizados que mejoran la experiencia de tu servidor y automatizan la gestión de la comunidad",
    botTypesTitle: "Tipos de Bots que Creo",
    whyChooseTitle: "¿Por qué elegir mis bots?",
    popular: "Popular",
    featuresCount: "más características",
    moderationTitle: "Bots de Moderación",
    moderationDesc: "Gestión avanzada de servidores con herramientas de moderación automatizadas",
    musicTitle: "Bots de Música",
    musicDesc: "Reproducción de música de alta calidad con soporte para bibliotecas extensas",
    gamingTitle: "Bots de Juegos",
    gamingDesc: "Juegos interactivos y herramientas de gestión de comunidades de jugadores",
    utilityTitle: "Bots de Utilidad",
    utilityDesc: "Herramientas útiles para la gestión de servidores y comodidad del usuario",
    economyTitle: "Bots de Economía",
    economyDesc: "Sistemas de moneda virtual con tiendas y recompensas",
    customBotsTitle: "Bots Personalizados",
    customBotsDesc: "Soluciones a medida para las necesidades específicas de tu servidor",
    lightningFast: "Rápido como el rayo",
    lightningFastDesc: "Rendimiento optimizado con latencia mínima",
    dataStorage: "Almacenamiento de Datos",
    dataStorageDesc: "Soluciones de base de datos seguras para datos persistentes",
    secureReliable: "Seguro y Confiable",
    secureReliableDesc: "Seguridad de nivel empresarial y 99.9% de tiempo de actividad",
    analyticsDashboard: "Panel de Análisis",
    analyticsDashboardDesc: "Información detallada y estadísticas de uso",
    multiLanguage: "Multi-idioma",
    multiLanguageDesc: "Soporte para múltiples idiomas y regiones",
    support247: "Soporte 24/7",
    support247Desc: "Mantenimiento y actualizaciones las 24 horas",

    // Contact Section
    getInTouch: "Ponte en contacto",
    contactTagline: "Envíame un mensaje y te responderé lo antes posible.",
    connectOnSocial: "Conecta en redes sociales",
    sendMessage: "Enviar un mensaje",
    name: "Nombre",
    emailAddress: "Correo electrónico",
    subject: "Asunto",
    projectType: "Tipo de proyecto",
    message: "Mensaje",
    send: "Enviar mensaje",
    sending: "Enviando...",
    selectProjectType: "Selecciona un tipo de proyecto",
    webDevelopment: "Desarrollo Web",
    discordBot: "Bot de Discord",
    uiuxDesign: "Diseño UI/UX",
    mobileApp: "Aplicación Móvil",
    messagePlaceholder: "Cuéntame sobre tu proyecto...",
    messageSuccess: "¡Mensaje enviado con éxito!",
    messageSuccessDesc: "Gracias por contactarme. Te responderé pronto.",
    messageError: "Error al enviar el mensaje. Por favor, inténtalo de nuevo.",

    // Footer
    footerDesc: "Creando experiencias digitales excepcionales y bots de Discord potentes que hacen prosperar a las comunidades.",
    quickLinks: "Enlaces rápidos",
    services: "Servicios",
    consulting: "Consultoría",
    backToTop: "Volver arriba",
    rights: "Todos los derechos reservados. Hecho con",
    andLotsOf: "y mucho",

    // Discord Presence
    discordPresence: "Presencia en Discord",
    online: "En línea",
    idle: "Ausente",
    dnd: "No molestar",
    offline: "Desconectado",
    available: "Disponible",
    viewProfile: "Ver perfil",

    // Bot Features
    autoModeration: "Moderación automática",
    warningSystem: "Sistema de advertencias",
    roleManagement: "Gestión de roles",
    auditLogging: "Registro de auditoría",
    youtubeSpotify: "YouTube/Spotify",
    playlists: "Listas de reproducción",
    audioEffects: "Efectos de audio",
    voiceChannels: "Canales de voz",
    miniGames: "Mini juegos",
    tournaments: "Torneos",
    statsTracking: "Seguimiento de estadísticas",
    lfgSystem: "Sistema LFG",
    customCommands: "Comandos personalizados",
    reminders: "Recordatorios",
    polls: "Encuestas",
    welcomeMessages: "Mensajes de bienvenida",
    virtualCurrency: "Moneda virtual",
    shopSystem: "Sistema de tienda",
    dailyRewards: "Recompensas diarias",
    gamblingGames: "Juegos de azar",
    customFeatures: "Funciones a medida",
    apiIntegration: "Integración de API",
    databaseDesign: "Diseño de base de datos",
    uniqueCommands: "Comandos únicos",
  },

  fr: {
    // Navigation
    home: "Accueil",
    about: "À Propos",
    projects: "Projets",
    discordBots: "Bots Discord",
    contact: "Contact",
    technologies: "Technologies",

    // Hero Section
    helloIm: "Bonjour, je suis",
    iBuild: "Je crée",
    amazingWebsites: "des sites web incroyables",
    discordBots2: "des bots Discord",
    userExperiences: "des expériences utilisateur",
    digitalSolutions: "des solutions numériques",
    customApplications: "des applications personnalisées",
    heroDescription: "Développeur frontend et spécialiste des bots Discord, axé sur la création d'applications web exceptionnelles et de solutions d'automatisation intelligentes",
    viewMyWork: "Voir mon travail",
    letsConnect: "Connectons-nous",
    github: "GitHub",
    projectsCompleted: "Projets Terminés",
    discordBotsCount: "Bots Discord",
    supportAvailable: "Support Disponible",

    // About Section
    aboutMe: "À Propos de Moi",
    aboutTagline: "Développeur frontend et spécialiste des bots Discord, axé sur la création d'expériences numériques exceptionnelles.",
    aboutDescription: "Salut ! Je suis orzz5, un développeur frontend et spécialiste des bots Discord qui crée des expériences numériques belles et fonctionnelles. J'aide à donner vie aux idées grâce à des applications React et des bots Discord personnalisés.",
    problemSolver: "Solutionneur",
    creativeThinker: "Penseur créatif",
    teamPlayer: "Esprit d'équipe",
    fastLearner: "Apprentissage rapide",
    cleanCode: "Code Propre",
    performance: "Performance",
    versionControl: "Contrôle de Version",
    debugging: "Débogage",
    expert: "Expert",
    frontendDev: "Développement Frontend",
    backendDev: "Développement Backend",
    mobileDev: "Développement Mobile",
    cloudDev: "Cloud et DevOps",
    skillsExpertise: "Compétences et Expertise",
    whatIOffer: "Ce que je propose",
    webDevTitle: "Développement Web",
    webDevDesc: "Construction d'applications web réactives, rapides et belles avec des technologies modernes",
    discordDevTitle: "Bots Discord",
    discordDevDesc: "Bots Discord personnalisés pour la modération, le divertissement, l'automatisation et la gestion de communauté",
    designTitle: "Design UI/UX",
    designDesc: "Création d'interfaces utilisateur intuitives et visuellement attrayantes qui ravissent les utilisateurs",
    perfOptTitle: "Optimisation des Performances",
    perfOptDesc: "Optimisation des applications pour la vitesse, le SEO et la meilleure expérience utilisateur",

    // Technologies Section
    whatIUse: "Ce que j'utilise",
    toolsDaily: "Outils et technologies avec lesquels je travaille quotidiennement",

    // Projects Section
    projectsTitle: "Projets",
    projectsTagline: "Prochainement - présentation de mes derniers travaux en développement frontend et création de bots Discord",
    allProjects: "Tous les projets",
    webApps: "Applications Web",
    projectsComingSoon: "Projets à venir",
    projectsSoonDesc: "Je travaille actuellement sur des projets passionnants qui seront présentés ici bientôt. Revenez plus tard pour voir mes derniers travaux.",
    getNotified: "Être notifié",
    viewAllProjects: "Voir tous les projets",
    keyFeatures: "Caractéristiques clés :",

    // Discord Services Section
    discordBotDev: "Développement de Bots Discord",
    discordDesc: "Créez des bots Discord puissants et personnalisés qui améliorent l'expérience de votre serveur et automatisent la gestion de la communauté",
    botTypesTitle: "Types de bots que je crée",
    whyChooseTitle: "Pourquoi choisir mes bots ?",
    popular: "Populaire",
    featuresCount: "caractéristiques supplémentaires",
    moderationTitle: "Bots de Modération",
    moderationDesc: "Gestion avancée de serveur avec des outils de modération automatisés",
    musicTitle: "Bots de Musique",
    musicDesc: "Lecture de musique de haute qualité avec une prise en charge étendue des bibliothèques",
    gamingTitle: "Bots de Jeux",
    gamingDesc: "Jeux interactifs et outils de gestion de communauté de joueurs",
    utilityTitle: "Bots d'Utilité",
    utilityDesc: "Outils utiles pour la gestion de serveur et le confort des utilisateurs",
    economyTitle: "Bots d'Économie",
    economyDesc: "Systèmes de monnaie virtuelle avec boutiques et récompenses",
    customBotsTitle: "Bots Personnalisés",
    customBotsDesc: "Solutions sur mesure pour les besoins spécifiques de votre serveur",
    lightningFast: "Rapide comme l'éclair",
    lightningFastDesc: "Performances optimisées avec une latence minimale",
    dataStorage: "Stockage de Données",
    dataStorageDesc: "Solutions de base de données sécurisées pour les données persistantes",
    secureReliable: "Sûr et Fiable",
    secureReliableDesc: "Sécurité de niveau entreprise et 99,9 % de temps de fonctionnement",
    analyticsDashboard: "Tableau de Bord Analytique",
    analyticsDashboardDesc: "Informations détaillées et statistiques d'utilisation",
    multiLanguage: "Multi-langue",
    multiLanguageDesc: "Support pour plusieurs langues et régions",
    support247: "Support 24/7",
    support247Desc: "Maintenance et mises à jour 24h/24",

    // Contact Section
    getInTouch: "Contactez-moi",
    contactTagline: "Envoyez-moi un message et je vous répondrai dès que possible.",
    connectOnSocial: "Suivez-moi sur les réseaux",
    sendMessage: "Envoyer un message",
    name: "Nom",
    emailAddress: "Adresse e-mail",
    subject: "Sujet",
    projectType: "Type de projet",
    message: "Message",
    send: "Envoyer le message",
    sending: "Envoi en cours...",
    selectProjectType: "Sélectionnez un type de projet",
    webDevelopment: "Développement Web",
    discordBot: "Bot Discord",
    uiuxDesign: "Design UI/UX",
    mobileApp: "Application Mobile",
    messagePlaceholder: "Parlez-moi de votre projet...",
    messageSuccess: "Message envoyé avec succès !",
    messageSuccessDesc: "Merci de m'avoir contacté. Je vous répondrai bientôt.",
    messageError: "Échec de l'envoi du message. Veuillez réessayer.",

    // Footer
    footerDesc: "Création d'expériences numériques exceptionnelles et de bots Discord puissants qui font prospérer les communautés.",
    quickLinks: "Liens rapides",
    services: "Services",
    consulting: "Consultation",
    backToTop: "Retour en haut",
    rights: "Tous droits réservés. Fait avec",
    andLotsOf: "et beaucoup de",

    // Discord Presence
    discordPresence: "Présence Discord",
    online: "En ligne",
    idle: "Inactif",
    dnd: "Ne pas déranger",
    offline: "Hors ligne",
    available: "Disponible",
    viewProfile: "Voir le profil",

    // Bot Features
    autoModeration: "Modération automatique",
    warningSystem: "Système d'avertissement",
    roleManagement: "Gestion des rôles",
    auditLogging: "Logs d'audit",
    youtubeSpotify: "YouTube/Spotify",
    playlists: "Listes de lecture",
    audioEffects: "Effets audio",
    voiceChannels: "Salons vocaux",
    miniGames: "Mini-jeux",
    tournaments: "Tournois",
    statsTracking: "Suivi des stats",
    lfgSystem: "Système LFG",
    customCommands: "Commandes personnalisées",
    reminders: "Rappels",
    polls: "Sondages",
    welcomeMessages: "Messages de bienvenue",
    virtualCurrency: "Monnaie virtuelle",
    shopSystem: "Système de boutique",
    dailyRewards: "Récompenses quotidiennes",
    gamblingGames: "Jeux de hasard",
    customFeatures: "Fonctionnalités sur mesure",
    apiIntegration: "Intégration API",
    databaseDesign: "Conception de base de données",
    uniqueCommands: "Commandes uniques",
  }
};

const LanguageContext = createContext();

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language][key] || translations['en'][key] || key;
  };

  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  React.useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'en';
    setLanguage(savedLanguage);
  }, []);

  return (
    <LanguageContext.Provider value={{ language, t, changeLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageContext;
